
import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
// const re = Rel({ subsets: ['latin'] })
// const raleway = Raleway({subsets:["Raleway"]});

export const metadata: Metadata = {
  title: "Texi Reservation App",
  description: "Generated by Texi Reservation App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar /> {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
